# Generated by Django 2.2.18 on 2021-02-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210204_0354"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firstname",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
